# Generated by Django 5.1.2 on 2024-11-05 17:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ajustes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('averia', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('nota', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones', to='ajustes.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reparación',
                'verbose_name_plural': 'Reparaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dispositivo', models.CharField(choices=[('movil', 'Móvil'), ('consola', 'Consola'), ('ordenador', 'Ordenador')], max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('bloqueo', models.CharField(choices=[('sin_bloqueo', 'Sin Bloqueo'), ('patron', 'Patrón'), ('pin', 'PIN'), ('huella', 'Huella'), ('facial', 'Facial')], default='sin_bloqueo', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.TextField(blank=True, null=True)),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sat.reparacion')),
            ],
        ),
    ]
