# Generated by Django 5.1.2 on 2024-12-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='horario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='politica_privacidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='terminos_condiciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
