# Generated by Django 5.1.2 on 2024-12-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0003_alter_establecimiento_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha_registro',
        ),
    ]
