# Generated by Django 5.1.2 on 2024-10-31 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajustes.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
